# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
#  pipelines:
#    - pipeline: P1
#     #  project: Project1
#      source: jainamanjain.Test2
  pipelines:
   - pipeline: P1
     project: Project1
     source: jainamanjain.Test2

  repositories:
   - repository: githubRepo1
     type: GitHub
     endpoint: GithubConnection
     source: amjn/Test2
     name: amjn/Test2
   - repository: bitbucket1
     type: BitBucket
     endpoint: BitBucketConnection
     source: amja_bitbucket/bitbucketrepo
     name: amja_bitbucket/bitbucketrepo
   - repository: AzRepo1
     type: git
     name: AzureRepo1

  containers:
  - container: ACRResourceLatest
    type: ACR
    azureSubscription: ARM_Manual
    resourceGroup: anumitaReg
    registry: abhisheaAcr
    repository: acrcontainerrepository1111
  - container: DockerHubContainer
    endpoint: DockerHubConnection
    image: amjadocker/dockercontainerrepository1111
jobs:
  - job: J1
    pool: Default
    steps:
    # - checkout: AzRepo1
    - powershell: |
            ls $(Build.ArtifactStagingDirectory)/ 

  - deployment: deploymentJob4
    environment: envionment4
    pool: Default
    strategy:
     runOnce:
      deploy:
       steps:
        # - checkout: self
        # - checkout: githubRepo1
        - checkout: bitbucket1
        # - checkout: AzRepo1
        - powershell: |
            ls $(Build.ArtifactStagingDirectory)/